name: nano
model:
  n_tokens: 23
  d_embedding: 256
  d_model: 256
  n_encoder_layers: 6
  aa_kernel_size: 7
  r: 128
  n_region: 3
  r_embedding: 4
  r_model: 256
  n_pos_model: 256
  max_len: 100
  sum_d_model: 512
  dual_layers: 6
  att_model: 512
  dim_feedforward: 256
  nhead: 8
  cs_layers: 5
  dropout: 0.1
  activation: gelu
train:
  seed: 2023
  max_iter: 100000
  batch_acc: 1
  valid_step: 250
  split_ratio: 0.95
  batch_size: 128
  num_workers: 4
  clip_norm: 10
  optimizer:
    type: Adam
    lr: 0.0001
    weight_decay: 0.01
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.7
    patience: 20
    min_lr: 1.0e-05
amp:
  motif_active_file: data/motif/AMP_act_Motifs.csv
  motif_hemolytic_file: data/motif/AMP_hom_negMotifs.csv
  mode: de
